blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/cavrilionis/centsair/discussions/new
    about: Ask questions and discuss with other centsair community members
  - name: Blank issue
    url: https://github.com/cavrilionis/centsair/issues/new
    about: Please note that GitHub Discussions should be used in most cases instead
