name: Feature request
description: Suggest a new data source, chart, analysis, enhancement to an existing chart, etc.
labels: ['New Feature', 'Needs Triage']

body:
- type: markdown
  attributes:
    value: >
      #### If you want to propose a new feature, please refer first to the [contributing guidelines](https://github.com/cavrilionis/centsair/CONTRIBUTING.md).
- type: textarea
  attributes:
    label: Describe the workflow you want to enable
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe your proposed solution
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you've considered, if relevant
- type: textarea
  attributes:
    label: Additional context
